#!/bin/bash
#
# Copyright (c) 2018 Raptor Engineering, LLC
# Released under the terms of the AGPL v3

set -e

NEW_ULTRATURBO_MHZ="$1"
VOLTAGE_RATIO="$2"
INDIR="$3"
INFILE="$4"
OUTFILE="$5"
SOURCE_BUCKET=2
DEST_BUCKET=5

P9_ALLOWED_BUCKET_NEST_MHZ=(0 1600 1866 2000 2133 2400 2666)

NEW_NEST_FREQUENCY=${P9_ALLOWED_BUCKET_NEST_MHZ[$DEST_BUCKET]}

rm -rf bucket_copy
mkdir bucket_copy
../reverseVpd.py -v ${INDIR}/${INFILE}.bin -o bucket_copy -r &> /dev/null

cp ${INDIR}/${INFILE}.bin ${OUTFILE}.bin

for i in `seq 0 5`; do
	POUND_V=$(./extract_buckets_from_tvpd.py "#V" bucket_copy/${INFILE}-LRP${i}.tvpd)
	if [[ "$POUND_V" != "" ]]; then
		./update_poundv_buckets.py ${SOURCE_BUCKET} ${DEST_BUCKET} ${NEW_NEST_FREQUENCY} ${NEW_ULTRATURBO_MHZ} ${VOLTAGE_RATIO} ${POUND_V}
		./find_replace_binary_string.py ${OUTFILE}.bin search.bin replace.bin
	fi
done

POUND_W=$(./extract_buckets_from_tvpd.py "#W" bucket_copy/${INFILE}-CRP0.tvpd)
if [[ "$POUND_W" != "" ]]; then
	./update_poundw_buckets.py ${SOURCE_BUCKET} ${DEST_BUCKET} ${POUND_W}
	./find_replace_binary_string.py ${OUTFILE}.bin search.bin replace.bin
fi
